#!/bin/sh
username="undefined"
su $username -c "rsync -av --delete --rsh=ssh /home/$username/Documents /home/$username/Pictures /home/$username/Videos /home/$username/Downloads data@pidata:/home/data"
