#!/bin/sh

set -e

ostype="$(lsb_release -si)"

if [ "$ostype" != "Ubuntu" -a "$ostype" != "Linuxmint" ]; then
	echo "This script might not work for your OS"
	echo "Please proceed manually..."
	exit 1
fi


sudo apt remove docker docker-engine docker.io containerd runc || true

sudo apt update
sudo apt install -y apt-transport-https ca-certificates curl gnupg lsb-release
curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
if [ "$(lsb_release -si)" == "Ubuntu" ]; then
	echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(lsb_release -sc) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
else
	echo "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu $(head -1 /etc/apt/sources.list | rev | cut -d " " -f2 | rev) stable" | sudo tee /etc/apt/sources.list.d/docker.list > /dev/null
fi

sudo apt update
sudo apt install docker-ce docker-ce-cli containerd.io docker-compose-plugin
