#!/usr/bin/env perl

use warnings;
use strict;

my $in;
if (@ARGV < 1) {
  $in = "STDIN";
} else {
  open($in, '<', $ARGV[0]) or die $!;
}

my @lines = <$in>;
my $filecontents = join("", @lines[0..$#lines]);

my $cleared = "";
foreach ("$filecontents" =~ /\w+\s\*?\w+\s*\(.*\)\s*\{/g) {
  s/\n//g;
  $cleared = substr($_, 0, -1);
  print "$cleared;\n";
}

close($in);
