#!/usr/bin/env perl

use warnings;
use strict;

my $in;
if (@ARGV < 1) {
  $in = "STDIN";
} else {
  open($in, '<', $ARGV[0]) or die $!;
}

my @lines = <$in>;
my $filecontents = join("", @lines[0..$#lines]);

my @fn_names = "$filecontents" =~ /[a-z]+\s\w+\(.*\)\s\{/g;
my $test = "$filecontents" =~ /[a-z]+\s\w+\(.*\)\s\{/;
print $test;

my $cleared;
foreach (@fn_names) {
  $cleared = substr($_, 0, -2);
  print "$cleared;\n";
}

close($in);
