#!/bin/bash

if [[ ! "$1" =~ [0-9].[0-9] ]]; then
	echo "You must specify a brightness as a float" >&2
	exit 1
fi

output="$(xrandr -q | grep "connected" | head -1 | cut -d " " -f 1)"
xrandr --output "$output" --brightness "$1"
