#!/usr/bin/env python3

import sys

if len(sys.argv) != 2:
    print("Usage: tocgen file.md")
    sys.exit(1)

def get_link(line):
    link = line.replace(":", "")
    link = link.replace("(", "")
    link = link.replace(")", "")
    link = link.replace("`", "")
    link = link.replace("/", "")
    link = link.replace("\\", "")
    link = link.replace(">", "")
    link = link.replace("<", "")
    link = link.replace("  ", " ")
    link = link.lower()
    link = link.strip("# ")
    link = "#" + link.replace(" ", "-")
    return link

with open(sys.argv[1], "r") as file:
    in_code_block = False
    for line in file:
        line = line.strip()
        if len(line) == 0:
            continue
        if (line[0:3] == "```"):
            in_code_block = not in_code_block
        if (in_code_block):
            continue
        if (line[0:4] == "### "):
            print("\t\t1. [" + line[4:] + "]" + "(" + sys.argv[1] + get_link(line) + ")")
        elif (line[0:3] == "## "):
            print("\t1. [" + line[3:] + "]" + "(" + sys.argv[1] + get_link(line) + ")")
        elif (line[0:2] == "# "):
            print("1. [" + line[2:] + "]" + "(" + sys.argv[1] + get_link(line) + ")")
