#!/bin/bash

set -e

usage () {
  echo "${0##*/}: <markdown file to view rendered>" >&2
  exit 1
}

FILE_EXT="html"

# tab completion for markdown files only
if [[ -n "$COMP_LINE" ]]; then
  prefix=$(echo "$COMP_LINE" | cut -d " " -f 2)
  ls -1 *.md 2>/dev/null | grep ^$prefix
  exit 0
fi

# Test if commit message is given
(( $# != 1 )) && usage

pandoc --mathjax="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js" --standalone -o "./tmpmdrender.$FILE_EXT" "$1"
firefox "./tmpmdrender.$FILE_EXT" &>/dev/null &

sleep 3 # without this delay firefox will show file not found since the file will be immediatly deleted
rm "./tmpmdrender.$FILE_EXT"
