#!/bin/bash
#
# zetsearch [-t/--tag tagname] [-h/--header-only] keyword
# Show all Zet IDs (and their titles) whose files contain <keyword>
# -t/--tag selects only zets with the given tag
# -h/--header-only means that keyword will only be looked for in the title
# of the Zets
# (maybe not optimal implementation)

usage () {
	echo "${0##*/}: [-t/--tag tagname] [-h/--header-only] keyword" >&2
	exit 1
}

keyword=
tag=
header_only=

while [[ -n "$1" ]]; do
	case "$1" in
		-t | --tag)		shift; tag="#$1" ;;
		-h | --header-only)	header_only=1 ;;
		-*)			echo "Unknown option: $1" >&2; usage ;;
		*)			keyword="$1" ;;
	esac
	shift
done

if [[ -z "$keyword" && -z "$tag" ]]; then
	echo "Either a tag or a keyword is required" >&2
	usage
fi

for file in $(grep --ignore-case --files-with-matches "$keyword" */*); do
	if [[ -z $(grep --ignore-case "$tag" "$file") ]]; then
 		continue
 	fi

	# print the Zet ID followed by the title
	if [[ -n "$header_only" ]]; then
		echo "${file%%/*} $(head -1 "$file")" | grep --ignore-case "$keyword"
	else
		echo "${file%%/*} $(head -1 "$file")"
	fi
done
