#!/bin/sh

set -e

echo "install dependencies..."
if [ -e /etc/arch-release ]; then
  sudo pacman -Sy base-devel libx11
else
  sudo apt update
  sudo apt install build-essential libx11-dev
fi

echo "obtain the source code..."
mkdir -p "$HOME/src"
cd "$HOME/src"
git clone https://git.suckless.org/st

echo "configuring..."
cd st
# config: change default font size to 16 (default 12)
cp config.def.h config.h
sed -i "s/pixelsize=12/pixelsize=16/" config.h

echo "installing..."
sudo make clean install
